
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type EnumUserStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.UserStatus | Prisma.EnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserStatusFilter<$PrismaModel> | $Enums.UserStatus
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumUserStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserStatus | Prisma.EnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserStatusWithAggregatesFilter<$PrismaModel> | $Enums.UserStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserStatusFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type BigIntFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntFilter<$PrismaModel> | bigint | number
}

export type EnumCurrencyFilter<$PrismaModel = never> = {
  equals?: $Enums.Currency | Prisma.EnumCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCurrencyFilter<$PrismaModel> | $Enums.Currency
}

export type EnumWalletStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletStatus | Prisma.EnumWalletStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletStatusFilter<$PrismaModel> | $Enums.WalletStatus
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type BigIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntWithAggregatesFilter<$PrismaModel> | bigint | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntFilter<$PrismaModel>
}

export type EnumCurrencyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Currency | Prisma.EnumCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCurrencyWithAggregatesFilter<$PrismaModel> | $Enums.Currency
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCurrencyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCurrencyFilter<$PrismaModel>
}

export type EnumWalletStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletStatus | Prisma.EnumWalletStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletStatusWithAggregatesFilter<$PrismaModel> | $Enums.WalletStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWalletStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWalletStatusFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumWalletTransactionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletTransactionType | Prisma.EnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletTransactionTypeFilter<$PrismaModel> | $Enums.WalletTransactionType
}

export type EnumWalletTransactionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletTransactionType | Prisma.EnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletTransactionTypeWithAggregatesFilter<$PrismaModel> | $Enums.WalletTransactionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWalletTransactionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWalletTransactionTypeFilter<$PrismaModel>
}

export type EnumMarketStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.MarketStatus | Prisma.EnumMarketStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMarketStatusFilter<$PrismaModel> | $Enums.MarketStatus
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type EnumMarketStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MarketStatus | Prisma.EnumMarketStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMarketStatusWithAggregatesFilter<$PrismaModel> | $Enums.MarketStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMarketStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMarketStatusFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumPredictionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionStatus | Prisma.EnumPredictionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionStatusFilter<$PrismaModel> | $Enums.PredictionStatus
}

export type EnumPredictionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionStatus | Prisma.EnumPredictionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionStatusWithAggregatesFilter<$PrismaModel> | $Enums.PredictionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPredictionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPredictionStatusFilter<$PrismaModel>
}

export type EnumPredictionTransactionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionTransactionType | Prisma.EnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionTransactionTypeFilter<$PrismaModel> | $Enums.PredictionTransactionType
}

export type EnumPredictionTransactionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionTransactionType | Prisma.EnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionTransactionTypeWithAggregatesFilter<$PrismaModel> | $Enums.PredictionTransactionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPredictionTransactionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPredictionTransactionTypeFilter<$PrismaModel>
}

export type EnumBetStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.BetStatus | Prisma.EnumBetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBetStatusFilter<$PrismaModel> | $Enums.BetStatus
}

export type EnumBetStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BetStatus | Prisma.EnumBetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBetStatusWithAggregatesFilter<$PrismaModel> | $Enums.BetStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBetStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBetStatusFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedEnumUserStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.UserStatus | Prisma.EnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserStatusFilter<$PrismaModel> | $Enums.UserStatus
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumUserStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserStatus | Prisma.EnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserStatus[] | Prisma.ListEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserStatusWithAggregatesFilter<$PrismaModel> | $Enums.UserStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserStatusFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedBigIntFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntFilter<$PrismaModel> | bigint | number
}

export type NestedEnumCurrencyFilter<$PrismaModel = never> = {
  equals?: $Enums.Currency | Prisma.EnumCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCurrencyFilter<$PrismaModel> | $Enums.Currency
}

export type NestedEnumWalletStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletStatus | Prisma.EnumWalletStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletStatusFilter<$PrismaModel> | $Enums.WalletStatus
}

export type NestedBigIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntWithAggregatesFilter<$PrismaModel> | bigint | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumCurrencyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Currency | Prisma.EnumCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Currency[] | Prisma.ListEnumCurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCurrencyWithAggregatesFilter<$PrismaModel> | $Enums.Currency
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCurrencyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCurrencyFilter<$PrismaModel>
}

export type NestedEnumWalletStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletStatus | Prisma.EnumWalletStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletStatus[] | Prisma.ListEnumWalletStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletStatusWithAggregatesFilter<$PrismaModel> | $Enums.WalletStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWalletStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWalletStatusFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedEnumWalletTransactionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletTransactionType | Prisma.EnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletTransactionTypeFilter<$PrismaModel> | $Enums.WalletTransactionType
}

export type NestedEnumWalletTransactionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WalletTransactionType | Prisma.EnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WalletTransactionType[] | Prisma.ListEnumWalletTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWalletTransactionTypeWithAggregatesFilter<$PrismaModel> | $Enums.WalletTransactionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWalletTransactionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWalletTransactionTypeFilter<$PrismaModel>
}

export type NestedEnumMarketStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.MarketStatus | Prisma.EnumMarketStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMarketStatusFilter<$PrismaModel> | $Enums.MarketStatus
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedEnumMarketStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MarketStatus | Prisma.EnumMarketStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MarketStatus[] | Prisma.ListEnumMarketStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMarketStatusWithAggregatesFilter<$PrismaModel> | $Enums.MarketStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMarketStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMarketStatusFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumPredictionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionStatus | Prisma.EnumPredictionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionStatusFilter<$PrismaModel> | $Enums.PredictionStatus
}

export type NestedEnumPredictionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionStatus | Prisma.EnumPredictionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionStatus[] | Prisma.ListEnumPredictionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionStatusWithAggregatesFilter<$PrismaModel> | $Enums.PredictionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPredictionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPredictionStatusFilter<$PrismaModel>
}

export type NestedEnumPredictionTransactionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionTransactionType | Prisma.EnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionTransactionTypeFilter<$PrismaModel> | $Enums.PredictionTransactionType
}

export type NestedEnumPredictionTransactionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PredictionTransactionType | Prisma.EnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PredictionTransactionType[] | Prisma.ListEnumPredictionTransactionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPredictionTransactionTypeWithAggregatesFilter<$PrismaModel> | $Enums.PredictionTransactionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPredictionTransactionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPredictionTransactionTypeFilter<$PrismaModel>
}

export type NestedEnumBetStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.BetStatus | Prisma.EnumBetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBetStatusFilter<$PrismaModel> | $Enums.BetStatus
}

export type NestedEnumBetStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BetStatus | Prisma.EnumBetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BetStatus[] | Prisma.ListEnumBetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBetStatusWithAggregatesFilter<$PrismaModel> | $Enums.BetStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBetStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBetStatusFilter<$PrismaModel>
}


