
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  SUSPEND: 'SUSPEND',
  DELETED: 'DELETED'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const UserRoles = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  DELETED: 'DELETED'
} as const

export type UserRoles = (typeof UserRoles)[keyof typeof UserRoles]


export const WalletStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

export type WalletStatus = (typeof WalletStatus)[keyof typeof WalletStatus]


export const Currency = {
  USD: 'USD',
  EUR: 'EUR',
  JPY: 'JPY'
} as const

export type Currency = (typeof Currency)[keyof typeof Currency]


export const WalletTransactionType = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  BET: 'BET',
  PAYOUT: 'PAYOUT',
  REFUND: 'REFUND',
  CANCEL: 'CANCEL'
} as const

export type WalletTransactionType = (typeof WalletTransactionType)[keyof typeof WalletTransactionType]


export const MarketStatus = {
  UPCOMING: 'UPCOMING',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  RESOLVED: 'RESOLVED',
  PAYOUT: 'PAYOUT',
  CANCELLED: 'CANCELLED'
} as const

export type MarketStatus = (typeof MarketStatus)[keyof typeof MarketStatus]


export const PredictionStatus = {
  UPCOMING: 'UPCOMING',
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  WON: 'WON',
  LOST: 'LOST',
  CANCELLED: 'CANCELLED'
} as const

export type PredictionStatus = (typeof PredictionStatus)[keyof typeof PredictionStatus]


export const PredictionTransactionType = {
  BET: 'BET',
  REFUND: 'REFUND',
  CANCEL: 'CANCEL'
} as const

export type PredictionTransactionType = (typeof PredictionTransactionType)[keyof typeof PredictionTransactionType]


export const BetStatus = {
  PENDING: 'PENDING',
  LOCKED: 'LOCKED',
  WON: 'WON',
  LOST: 'LOST',
  PAYOUT: 'PAYOUT',
  CANCELLED: 'CANCELLED'
} as const

export type BetStatus = (typeof BetStatus)[keyof typeof BetStatus]
