
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Wallet: 'Wallet',
  WalletTransaction: 'WalletTransaction',
  Market: 'Market',
  Prediction: 'Prediction',
  PredictionTransaction: 'PredictionTransaction',
  Bet: 'Bet'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  display_name: 'display_name',
  email_address: 'email_address',
  password_hash: 'password_hash',
  status: 'status',
  roles: 'roles',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const WalletScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  balance: 'balance',
  currency: 'currency',
  reserved_amount: 'reserved_amount',
  status: 'status',
  version: 'version',
  updated_at: 'updated_at'
} as const

export type WalletScalarFieldEnum = (typeof WalletScalarFieldEnum)[keyof typeof WalletScalarFieldEnum]


export const WalletTransactionScalarFieldEnum = {
  id: 'id',
  wallet_id: 'wallet_id',
  prediction_id: 'prediction_id',
  type: 'type',
  currency: 'currency',
  amount: 'amount',
  balance_before: 'balance_before',
  balance_after: 'balance_after',
  created_at: 'created_at'
} as const

export type WalletTransactionScalarFieldEnum = (typeof WalletTransactionScalarFieldEnum)[keyof typeof WalletTransactionScalarFieldEnum]


export const MarketScalarFieldEnum = {
  id: 'id',
  title: 'title',
  status: 'status',
  closed_at: 'closed_at',
  updated_at: 'updated_at',
  resolved_at: 'resolved_at'
} as const

export type MarketScalarFieldEnum = (typeof MarketScalarFieldEnum)[keyof typeof MarketScalarFieldEnum]


export const PredictionScalarFieldEnum = {
  id: 'id',
  market_id: 'market_id',
  name: 'name',
  total_participants: 'total_participants',
  bet_sum: 'bet_sum',
  status: 'status',
  resolved_by_id: 'resolved_by_id',
  resolved_at: 'resolved_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  version: 'version'
} as const

export type PredictionScalarFieldEnum = (typeof PredictionScalarFieldEnum)[keyof typeof PredictionScalarFieldEnum]


export const PredictionTransactionScalarFieldEnum = {
  id: 'id',
  prediction_id: 'prediction_id',
  transaction_type: 'transaction_type',
  total_participants_before: 'total_participants_before',
  total_participants_after: 'total_participants_after',
  currency: 'currency',
  bet_amount: 'bet_amount',
  bet_sum_before: 'bet_sum_before',
  bet_sum_after: 'bet_sum_after',
  created_at: 'created_at'
} as const

export type PredictionTransactionScalarFieldEnum = (typeof PredictionTransactionScalarFieldEnum)[keyof typeof PredictionTransactionScalarFieldEnum]


export const BetScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  market_id: 'market_id',
  prediction_id: 'prediction_id',
  currency: 'currency',
  bet_amount: 'bet_amount',
  payout_amount: 'payout_amount',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  version: 'version'
} as const

export type BetScalarFieldEnum = (typeof BetScalarFieldEnum)[keyof typeof BetScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

