
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PredictionTransaction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PredictionTransaction
 * 
 */
export type PredictionTransactionModel = runtime.Types.Result.DefaultSelection<Prisma.$PredictionTransactionPayload>

export type AggregatePredictionTransaction = {
  _count: PredictionTransactionCountAggregateOutputType | null
  _avg: PredictionTransactionAvgAggregateOutputType | null
  _sum: PredictionTransactionSumAggregateOutputType | null
  _min: PredictionTransactionMinAggregateOutputType | null
  _max: PredictionTransactionMaxAggregateOutputType | null
}

export type PredictionTransactionAvgAggregateOutputType = {
  total_participants_before: number | null
  total_participants_after: number | null
  bet_amount: number | null
  bet_sum_before: number | null
  bet_sum_after: number | null
}

export type PredictionTransactionSumAggregateOutputType = {
  total_participants_before: number | null
  total_participants_after: number | null
  bet_amount: bigint | null
  bet_sum_before: bigint | null
  bet_sum_after: bigint | null
}

export type PredictionTransactionMinAggregateOutputType = {
  id: string | null
  prediction_id: string | null
  transaction_type: $Enums.PredictionTransactionType | null
  total_participants_before: number | null
  total_participants_after: number | null
  currency: $Enums.Currency | null
  bet_amount: bigint | null
  bet_sum_before: bigint | null
  bet_sum_after: bigint | null
  created_at: Date | null
}

export type PredictionTransactionMaxAggregateOutputType = {
  id: string | null
  prediction_id: string | null
  transaction_type: $Enums.PredictionTransactionType | null
  total_participants_before: number | null
  total_participants_after: number | null
  currency: $Enums.Currency | null
  bet_amount: bigint | null
  bet_sum_before: bigint | null
  bet_sum_after: bigint | null
  created_at: Date | null
}

export type PredictionTransactionCountAggregateOutputType = {
  id: number
  prediction_id: number
  transaction_type: number
  total_participants_before: number
  total_participants_after: number
  currency: number
  bet_amount: number
  bet_sum_before: number
  bet_sum_after: number
  created_at: number
  _all: number
}


export type PredictionTransactionAvgAggregateInputType = {
  total_participants_before?: true
  total_participants_after?: true
  bet_amount?: true
  bet_sum_before?: true
  bet_sum_after?: true
}

export type PredictionTransactionSumAggregateInputType = {
  total_participants_before?: true
  total_participants_after?: true
  bet_amount?: true
  bet_sum_before?: true
  bet_sum_after?: true
}

export type PredictionTransactionMinAggregateInputType = {
  id?: true
  prediction_id?: true
  transaction_type?: true
  total_participants_before?: true
  total_participants_after?: true
  currency?: true
  bet_amount?: true
  bet_sum_before?: true
  bet_sum_after?: true
  created_at?: true
}

export type PredictionTransactionMaxAggregateInputType = {
  id?: true
  prediction_id?: true
  transaction_type?: true
  total_participants_before?: true
  total_participants_after?: true
  currency?: true
  bet_amount?: true
  bet_sum_before?: true
  bet_sum_after?: true
  created_at?: true
}

export type PredictionTransactionCountAggregateInputType = {
  id?: true
  prediction_id?: true
  transaction_type?: true
  total_participants_before?: true
  total_participants_after?: true
  currency?: true
  bet_amount?: true
  bet_sum_before?: true
  bet_sum_after?: true
  created_at?: true
  _all?: true
}

export type PredictionTransactionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PredictionTransaction to aggregate.
   */
  where?: Prisma.PredictionTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PredictionTransactions to fetch.
   */
  orderBy?: Prisma.PredictionTransactionOrderByWithRelationInput | Prisma.PredictionTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PredictionTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PredictionTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PredictionTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PredictionTransactions
  **/
  _count?: true | PredictionTransactionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PredictionTransactionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PredictionTransactionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PredictionTransactionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PredictionTransactionMaxAggregateInputType
}

export type GetPredictionTransactionAggregateType<T extends PredictionTransactionAggregateArgs> = {
      [P in keyof T & keyof AggregatePredictionTransaction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePredictionTransaction[P]>
    : Prisma.GetScalarType<T[P], AggregatePredictionTransaction[P]>
}




export type PredictionTransactionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PredictionTransactionWhereInput
  orderBy?: Prisma.PredictionTransactionOrderByWithAggregationInput | Prisma.PredictionTransactionOrderByWithAggregationInput[]
  by: Prisma.PredictionTransactionScalarFieldEnum[] | Prisma.PredictionTransactionScalarFieldEnum
  having?: Prisma.PredictionTransactionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PredictionTransactionCountAggregateInputType | true
  _avg?: PredictionTransactionAvgAggregateInputType
  _sum?: PredictionTransactionSumAggregateInputType
  _min?: PredictionTransactionMinAggregateInputType
  _max?: PredictionTransactionMaxAggregateInputType
}

export type PredictionTransactionGroupByOutputType = {
  id: string
  prediction_id: string
  transaction_type: $Enums.PredictionTransactionType
  total_participants_before: number
  total_participants_after: number
  currency: $Enums.Currency
  bet_amount: bigint
  bet_sum_before: bigint
  bet_sum_after: bigint
  created_at: Date
  _count: PredictionTransactionCountAggregateOutputType | null
  _avg: PredictionTransactionAvgAggregateOutputType | null
  _sum: PredictionTransactionSumAggregateOutputType | null
  _min: PredictionTransactionMinAggregateOutputType | null
  _max: PredictionTransactionMaxAggregateOutputType | null
}

export type GetPredictionTransactionGroupByPayload<T extends PredictionTransactionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PredictionTransactionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PredictionTransactionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PredictionTransactionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PredictionTransactionGroupByOutputType[P]>
      }
    >
  >



export type PredictionTransactionWhereInput = {
  AND?: Prisma.PredictionTransactionWhereInput | Prisma.PredictionTransactionWhereInput[]
  OR?: Prisma.PredictionTransactionWhereInput[]
  NOT?: Prisma.PredictionTransactionWhereInput | Prisma.PredictionTransactionWhereInput[]
  id?: Prisma.StringFilter<"PredictionTransaction"> | string
  prediction_id?: Prisma.StringFilter<"PredictionTransaction"> | string
  transaction_type?: Prisma.EnumPredictionTransactionTypeFilter<"PredictionTransaction"> | $Enums.PredictionTransactionType
  total_participants_before?: Prisma.IntFilter<"PredictionTransaction"> | number
  total_participants_after?: Prisma.IntFilter<"PredictionTransaction"> | number
  currency?: Prisma.EnumCurrencyFilter<"PredictionTransaction"> | $Enums.Currency
  bet_amount?: Prisma.BigIntFilter<"PredictionTransaction"> | bigint | number
  bet_sum_before?: Prisma.BigIntFilter<"PredictionTransaction"> | bigint | number
  bet_sum_after?: Prisma.BigIntFilter<"PredictionTransaction"> | bigint | number
  created_at?: Prisma.DateTimeFilter<"PredictionTransaction"> | Date | string
}

export type PredictionTransactionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  prediction_id?: Prisma.SortOrder
  transaction_type?: Prisma.SortOrder
  total_participants_before?: Prisma.SortOrder
  total_participants_after?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  bet_amount?: Prisma.SortOrder
  bet_sum_before?: Prisma.SortOrder
  bet_sum_after?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type PredictionTransactionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PredictionTransactionWhereInput | Prisma.PredictionTransactionWhereInput[]
  OR?: Prisma.PredictionTransactionWhereInput[]
  NOT?: Prisma.PredictionTransactionWhereInput | Prisma.PredictionTransactionWhereInput[]
  prediction_id?: Prisma.StringFilter<"PredictionTransaction"> | string
  transaction_type?: Prisma.EnumPredictionTransactionTypeFilter<"PredictionTransaction"> | $Enums.PredictionTransactionType
  total_participants_before?: Prisma.IntFilter<"PredictionTransaction"> | number
  total_participants_after?: Prisma.IntFilter<"PredictionTransaction"> | number
  currency?: Prisma.EnumCurrencyFilter<"PredictionTransaction"> | $Enums.Currency
  bet_amount?: Prisma.BigIntFilter<"PredictionTransaction"> | bigint | number
  bet_sum_before?: Prisma.BigIntFilter<"PredictionTransaction"> | bigint | number
  bet_sum_after?: Prisma.BigIntFilter<"PredictionTransaction"> | bigint | number
  created_at?: Prisma.DateTimeFilter<"PredictionTransaction"> | Date | string
}, "id">

export type PredictionTransactionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  prediction_id?: Prisma.SortOrder
  transaction_type?: Prisma.SortOrder
  total_participants_before?: Prisma.SortOrder
  total_participants_after?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  bet_amount?: Prisma.SortOrder
  bet_sum_before?: Prisma.SortOrder
  bet_sum_after?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.PredictionTransactionCountOrderByAggregateInput
  _avg?: Prisma.PredictionTransactionAvgOrderByAggregateInput
  _max?: Prisma.PredictionTransactionMaxOrderByAggregateInput
  _min?: Prisma.PredictionTransactionMinOrderByAggregateInput
  _sum?: Prisma.PredictionTransactionSumOrderByAggregateInput
}

export type PredictionTransactionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PredictionTransactionScalarWhereWithAggregatesInput | Prisma.PredictionTransactionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PredictionTransactionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PredictionTransactionScalarWhereWithAggregatesInput | Prisma.PredictionTransactionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PredictionTransaction"> | string
  prediction_id?: Prisma.StringWithAggregatesFilter<"PredictionTransaction"> | string
  transaction_type?: Prisma.EnumPredictionTransactionTypeWithAggregatesFilter<"PredictionTransaction"> | $Enums.PredictionTransactionType
  total_participants_before?: Prisma.IntWithAggregatesFilter<"PredictionTransaction"> | number
  total_participants_after?: Prisma.IntWithAggregatesFilter<"PredictionTransaction"> | number
  currency?: Prisma.EnumCurrencyWithAggregatesFilter<"PredictionTransaction"> | $Enums.Currency
  bet_amount?: Prisma.BigIntWithAggregatesFilter<"PredictionTransaction"> | bigint | number
  bet_sum_before?: Prisma.BigIntWithAggregatesFilter<"PredictionTransaction"> | bigint | number
  bet_sum_after?: Prisma.BigIntWithAggregatesFilter<"PredictionTransaction"> | bigint | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"PredictionTransaction"> | Date | string
}

export type PredictionTransactionCreateInput = {
  id?: string
  prediction_id: string
  transaction_type: $Enums.PredictionTransactionType
  total_participants_before: number
  total_participants_after: number
  currency: $Enums.Currency
  bet_amount: bigint | number
  bet_sum_before: bigint | number
  bet_sum_after: bigint | number
  created_at?: Date | string
}

export type PredictionTransactionUncheckedCreateInput = {
  id?: string
  prediction_id: string
  transaction_type: $Enums.PredictionTransactionType
  total_participants_before: number
  total_participants_after: number
  currency: $Enums.Currency
  bet_amount: bigint | number
  bet_sum_before: bigint | number
  bet_sum_after: bigint | number
  created_at?: Date | string
}

export type PredictionTransactionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prediction_id?: Prisma.StringFieldUpdateOperationsInput | string
  transaction_type?: Prisma.EnumPredictionTransactionTypeFieldUpdateOperationsInput | $Enums.PredictionTransactionType
  total_participants_before?: Prisma.IntFieldUpdateOperationsInput | number
  total_participants_after?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  bet_amount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_before?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_after?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PredictionTransactionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prediction_id?: Prisma.StringFieldUpdateOperationsInput | string
  transaction_type?: Prisma.EnumPredictionTransactionTypeFieldUpdateOperationsInput | $Enums.PredictionTransactionType
  total_participants_before?: Prisma.IntFieldUpdateOperationsInput | number
  total_participants_after?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  bet_amount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_before?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_after?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PredictionTransactionCreateManyInput = {
  id?: string
  prediction_id: string
  transaction_type: $Enums.PredictionTransactionType
  total_participants_before: number
  total_participants_after: number
  currency: $Enums.Currency
  bet_amount: bigint | number
  bet_sum_before: bigint | number
  bet_sum_after: bigint | number
  created_at?: Date | string
}

export type PredictionTransactionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prediction_id?: Prisma.StringFieldUpdateOperationsInput | string
  transaction_type?: Prisma.EnumPredictionTransactionTypeFieldUpdateOperationsInput | $Enums.PredictionTransactionType
  total_participants_before?: Prisma.IntFieldUpdateOperationsInput | number
  total_participants_after?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  bet_amount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_before?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_after?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PredictionTransactionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prediction_id?: Prisma.StringFieldUpdateOperationsInput | string
  transaction_type?: Prisma.EnumPredictionTransactionTypeFieldUpdateOperationsInput | $Enums.PredictionTransactionType
  total_participants_before?: Prisma.IntFieldUpdateOperationsInput | number
  total_participants_after?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  bet_amount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_before?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  bet_sum_after?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PredictionTransactionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  prediction_id?: Prisma.SortOrder
  transaction_type?: Prisma.SortOrder
  total_participants_before?: Prisma.SortOrder
  total_participants_after?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  bet_amount?: Prisma.SortOrder
  bet_sum_before?: Prisma.SortOrder
  bet_sum_after?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type PredictionTransactionAvgOrderByAggregateInput = {
  total_participants_before?: Prisma.SortOrder
  total_participants_after?: Prisma.SortOrder
  bet_amount?: Prisma.SortOrder
  bet_sum_before?: Prisma.SortOrder
  bet_sum_after?: Prisma.SortOrder
}

export type PredictionTransactionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  prediction_id?: Prisma.SortOrder
  transaction_type?: Prisma.SortOrder
  total_participants_before?: Prisma.SortOrder
  total_participants_after?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  bet_amount?: Prisma.SortOrder
  bet_sum_before?: Prisma.SortOrder
  bet_sum_after?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type PredictionTransactionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  prediction_id?: Prisma.SortOrder
  transaction_type?: Prisma.SortOrder
  total_participants_before?: Prisma.SortOrder
  total_participants_after?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  bet_amount?: Prisma.SortOrder
  bet_sum_before?: Prisma.SortOrder
  bet_sum_after?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type PredictionTransactionSumOrderByAggregateInput = {
  total_participants_before?: Prisma.SortOrder
  total_participants_after?: Prisma.SortOrder
  bet_amount?: Prisma.SortOrder
  bet_sum_before?: Prisma.SortOrder
  bet_sum_after?: Prisma.SortOrder
}

export type EnumPredictionTransactionTypeFieldUpdateOperationsInput = {
  set?: $Enums.PredictionTransactionType
}



export type PredictionTransactionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  prediction_id?: boolean
  transaction_type?: boolean
  total_participants_before?: boolean
  total_participants_after?: boolean
  currency?: boolean
  bet_amount?: boolean
  bet_sum_before?: boolean
  bet_sum_after?: boolean
  created_at?: boolean
}, ExtArgs["result"]["predictionTransaction"]>

export type PredictionTransactionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  prediction_id?: boolean
  transaction_type?: boolean
  total_participants_before?: boolean
  total_participants_after?: boolean
  currency?: boolean
  bet_amount?: boolean
  bet_sum_before?: boolean
  bet_sum_after?: boolean
  created_at?: boolean
}, ExtArgs["result"]["predictionTransaction"]>

export type PredictionTransactionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  prediction_id?: boolean
  transaction_type?: boolean
  total_participants_before?: boolean
  total_participants_after?: boolean
  currency?: boolean
  bet_amount?: boolean
  bet_sum_before?: boolean
  bet_sum_after?: boolean
  created_at?: boolean
}, ExtArgs["result"]["predictionTransaction"]>

export type PredictionTransactionSelectScalar = {
  id?: boolean
  prediction_id?: boolean
  transaction_type?: boolean
  total_participants_before?: boolean
  total_participants_after?: boolean
  currency?: boolean
  bet_amount?: boolean
  bet_sum_before?: boolean
  bet_sum_after?: boolean
  created_at?: boolean
}

export type PredictionTransactionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "prediction_id" | "transaction_type" | "total_participants_before" | "total_participants_after" | "currency" | "bet_amount" | "bet_sum_before" | "bet_sum_after" | "created_at", ExtArgs["result"]["predictionTransaction"]>

export type $PredictionTransactionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PredictionTransaction"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    prediction_id: string
    transaction_type: $Enums.PredictionTransactionType
    total_participants_before: number
    total_participants_after: number
    currency: $Enums.Currency
    bet_amount: bigint
    bet_sum_before: bigint
    bet_sum_after: bigint
    created_at: Date
  }, ExtArgs["result"]["predictionTransaction"]>
  composites: {}
}

export type PredictionTransactionGetPayload<S extends boolean | null | undefined | PredictionTransactionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload, S>

export type PredictionTransactionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PredictionTransactionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PredictionTransactionCountAggregateInputType | true
  }

export interface PredictionTransactionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PredictionTransaction'], meta: { name: 'PredictionTransaction' } }
  /**
   * Find zero or one PredictionTransaction that matches the filter.
   * @param {PredictionTransactionFindUniqueArgs} args - Arguments to find a PredictionTransaction
   * @example
   * // Get one PredictionTransaction
   * const predictionTransaction = await prisma.predictionTransaction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PredictionTransactionFindUniqueArgs>(args: Prisma.SelectSubset<T, PredictionTransactionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PredictionTransaction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PredictionTransactionFindUniqueOrThrowArgs} args - Arguments to find a PredictionTransaction
   * @example
   * // Get one PredictionTransaction
   * const predictionTransaction = await prisma.predictionTransaction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PredictionTransactionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PredictionTransactionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PredictionTransaction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PredictionTransactionFindFirstArgs} args - Arguments to find a PredictionTransaction
   * @example
   * // Get one PredictionTransaction
   * const predictionTransaction = await prisma.predictionTransaction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PredictionTransactionFindFirstArgs>(args?: Prisma.SelectSubset<T, PredictionTransactionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PredictionTransaction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PredictionTransactionFindFirstOrThrowArgs} args - Arguments to find a PredictionTransaction
   * @example
   * // Get one PredictionTransaction
   * const predictionTransaction = await prisma.predictionTransaction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PredictionTransactionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PredictionTransactionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PredictionTransactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PredictionTransactionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PredictionTransactions
   * const predictionTransactions = await prisma.predictionTransaction.findMany()
   * 
   * // Get first 10 PredictionTransactions
   * const predictionTransactions = await prisma.predictionTransaction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const predictionTransactionWithIdOnly = await prisma.predictionTransaction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PredictionTransactionFindManyArgs>(args?: Prisma.SelectSubset<T, PredictionTransactionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PredictionTransaction.
   * @param {PredictionTransactionCreateArgs} args - Arguments to create a PredictionTransaction.
   * @example
   * // Create one PredictionTransaction
   * const PredictionTransaction = await prisma.predictionTransaction.create({
   *   data: {
   *     // ... data to create a PredictionTransaction
   *   }
   * })
   * 
   */
  create<T extends PredictionTransactionCreateArgs>(args: Prisma.SelectSubset<T, PredictionTransactionCreateArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PredictionTransactions.
   * @param {PredictionTransactionCreateManyArgs} args - Arguments to create many PredictionTransactions.
   * @example
   * // Create many PredictionTransactions
   * const predictionTransaction = await prisma.predictionTransaction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PredictionTransactionCreateManyArgs>(args?: Prisma.SelectSubset<T, PredictionTransactionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PredictionTransactions and returns the data saved in the database.
   * @param {PredictionTransactionCreateManyAndReturnArgs} args - Arguments to create many PredictionTransactions.
   * @example
   * // Create many PredictionTransactions
   * const predictionTransaction = await prisma.predictionTransaction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PredictionTransactions and only return the `id`
   * const predictionTransactionWithIdOnly = await prisma.predictionTransaction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PredictionTransactionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PredictionTransactionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PredictionTransaction.
   * @param {PredictionTransactionDeleteArgs} args - Arguments to delete one PredictionTransaction.
   * @example
   * // Delete one PredictionTransaction
   * const PredictionTransaction = await prisma.predictionTransaction.delete({
   *   where: {
   *     // ... filter to delete one PredictionTransaction
   *   }
   * })
   * 
   */
  delete<T extends PredictionTransactionDeleteArgs>(args: Prisma.SelectSubset<T, PredictionTransactionDeleteArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PredictionTransaction.
   * @param {PredictionTransactionUpdateArgs} args - Arguments to update one PredictionTransaction.
   * @example
   * // Update one PredictionTransaction
   * const predictionTransaction = await prisma.predictionTransaction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PredictionTransactionUpdateArgs>(args: Prisma.SelectSubset<T, PredictionTransactionUpdateArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PredictionTransactions.
   * @param {PredictionTransactionDeleteManyArgs} args - Arguments to filter PredictionTransactions to delete.
   * @example
   * // Delete a few PredictionTransactions
   * const { count } = await prisma.predictionTransaction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PredictionTransactionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PredictionTransactionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PredictionTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PredictionTransactionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PredictionTransactions
   * const predictionTransaction = await prisma.predictionTransaction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PredictionTransactionUpdateManyArgs>(args: Prisma.SelectSubset<T, PredictionTransactionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PredictionTransactions and returns the data updated in the database.
   * @param {PredictionTransactionUpdateManyAndReturnArgs} args - Arguments to update many PredictionTransactions.
   * @example
   * // Update many PredictionTransactions
   * const predictionTransaction = await prisma.predictionTransaction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PredictionTransactions and only return the `id`
   * const predictionTransactionWithIdOnly = await prisma.predictionTransaction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PredictionTransactionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PredictionTransactionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PredictionTransaction.
   * @param {PredictionTransactionUpsertArgs} args - Arguments to update or create a PredictionTransaction.
   * @example
   * // Update or create a PredictionTransaction
   * const predictionTransaction = await prisma.predictionTransaction.upsert({
   *   create: {
   *     // ... data to create a PredictionTransaction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PredictionTransaction we want to update
   *   }
   * })
   */
  upsert<T extends PredictionTransactionUpsertArgs>(args: Prisma.SelectSubset<T, PredictionTransactionUpsertArgs<ExtArgs>>): Prisma.Prisma__PredictionTransactionClient<runtime.Types.Result.GetResult<Prisma.$PredictionTransactionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PredictionTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PredictionTransactionCountArgs} args - Arguments to filter PredictionTransactions to count.
   * @example
   * // Count the number of PredictionTransactions
   * const count = await prisma.predictionTransaction.count({
   *   where: {
   *     // ... the filter for the PredictionTransactions we want to count
   *   }
   * })
  **/
  count<T extends PredictionTransactionCountArgs>(
    args?: Prisma.Subset<T, PredictionTransactionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PredictionTransactionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PredictionTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PredictionTransactionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PredictionTransactionAggregateArgs>(args: Prisma.Subset<T, PredictionTransactionAggregateArgs>): Prisma.PrismaPromise<GetPredictionTransactionAggregateType<T>>

  /**
   * Group by PredictionTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PredictionTransactionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PredictionTransactionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PredictionTransactionGroupByArgs['orderBy'] }
      : { orderBy?: PredictionTransactionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PredictionTransactionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPredictionTransactionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PredictionTransaction model
 */
readonly fields: PredictionTransactionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PredictionTransaction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PredictionTransactionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PredictionTransaction model
 */
export interface PredictionTransactionFieldRefs {
  readonly id: Prisma.FieldRef<"PredictionTransaction", 'String'>
  readonly prediction_id: Prisma.FieldRef<"PredictionTransaction", 'String'>
  readonly transaction_type: Prisma.FieldRef<"PredictionTransaction", 'PredictionTransactionType'>
  readonly total_participants_before: Prisma.FieldRef<"PredictionTransaction", 'Int'>
  readonly total_participants_after: Prisma.FieldRef<"PredictionTransaction", 'Int'>
  readonly currency: Prisma.FieldRef<"PredictionTransaction", 'Currency'>
  readonly bet_amount: Prisma.FieldRef<"PredictionTransaction", 'BigInt'>
  readonly bet_sum_before: Prisma.FieldRef<"PredictionTransaction", 'BigInt'>
  readonly bet_sum_after: Prisma.FieldRef<"PredictionTransaction", 'BigInt'>
  readonly created_at: Prisma.FieldRef<"PredictionTransaction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PredictionTransaction findUnique
 */
export type PredictionTransactionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * Filter, which PredictionTransaction to fetch.
   */
  where: Prisma.PredictionTransactionWhereUniqueInput
}

/**
 * PredictionTransaction findUniqueOrThrow
 */
export type PredictionTransactionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * Filter, which PredictionTransaction to fetch.
   */
  where: Prisma.PredictionTransactionWhereUniqueInput
}

/**
 * PredictionTransaction findFirst
 */
export type PredictionTransactionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * Filter, which PredictionTransaction to fetch.
   */
  where?: Prisma.PredictionTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PredictionTransactions to fetch.
   */
  orderBy?: Prisma.PredictionTransactionOrderByWithRelationInput | Prisma.PredictionTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PredictionTransactions.
   */
  cursor?: Prisma.PredictionTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PredictionTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PredictionTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PredictionTransactions.
   */
  distinct?: Prisma.PredictionTransactionScalarFieldEnum | Prisma.PredictionTransactionScalarFieldEnum[]
}

/**
 * PredictionTransaction findFirstOrThrow
 */
export type PredictionTransactionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * Filter, which PredictionTransaction to fetch.
   */
  where?: Prisma.PredictionTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PredictionTransactions to fetch.
   */
  orderBy?: Prisma.PredictionTransactionOrderByWithRelationInput | Prisma.PredictionTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PredictionTransactions.
   */
  cursor?: Prisma.PredictionTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PredictionTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PredictionTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PredictionTransactions.
   */
  distinct?: Prisma.PredictionTransactionScalarFieldEnum | Prisma.PredictionTransactionScalarFieldEnum[]
}

/**
 * PredictionTransaction findMany
 */
export type PredictionTransactionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * Filter, which PredictionTransactions to fetch.
   */
  where?: Prisma.PredictionTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PredictionTransactions to fetch.
   */
  orderBy?: Prisma.PredictionTransactionOrderByWithRelationInput | Prisma.PredictionTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PredictionTransactions.
   */
  cursor?: Prisma.PredictionTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PredictionTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PredictionTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PredictionTransactions.
   */
  distinct?: Prisma.PredictionTransactionScalarFieldEnum | Prisma.PredictionTransactionScalarFieldEnum[]
}

/**
 * PredictionTransaction create
 */
export type PredictionTransactionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * The data needed to create a PredictionTransaction.
   */
  data: Prisma.XOR<Prisma.PredictionTransactionCreateInput, Prisma.PredictionTransactionUncheckedCreateInput>
}

/**
 * PredictionTransaction createMany
 */
export type PredictionTransactionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PredictionTransactions.
   */
  data: Prisma.PredictionTransactionCreateManyInput | Prisma.PredictionTransactionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PredictionTransaction createManyAndReturn
 */
export type PredictionTransactionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * The data used to create many PredictionTransactions.
   */
  data: Prisma.PredictionTransactionCreateManyInput | Prisma.PredictionTransactionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PredictionTransaction update
 */
export type PredictionTransactionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * The data needed to update a PredictionTransaction.
   */
  data: Prisma.XOR<Prisma.PredictionTransactionUpdateInput, Prisma.PredictionTransactionUncheckedUpdateInput>
  /**
   * Choose, which PredictionTransaction to update.
   */
  where: Prisma.PredictionTransactionWhereUniqueInput
}

/**
 * PredictionTransaction updateMany
 */
export type PredictionTransactionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PredictionTransactions.
   */
  data: Prisma.XOR<Prisma.PredictionTransactionUpdateManyMutationInput, Prisma.PredictionTransactionUncheckedUpdateManyInput>
  /**
   * Filter which PredictionTransactions to update
   */
  where?: Prisma.PredictionTransactionWhereInput
  /**
   * Limit how many PredictionTransactions to update.
   */
  limit?: number
}

/**
 * PredictionTransaction updateManyAndReturn
 */
export type PredictionTransactionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * The data used to update PredictionTransactions.
   */
  data: Prisma.XOR<Prisma.PredictionTransactionUpdateManyMutationInput, Prisma.PredictionTransactionUncheckedUpdateManyInput>
  /**
   * Filter which PredictionTransactions to update
   */
  where?: Prisma.PredictionTransactionWhereInput
  /**
   * Limit how many PredictionTransactions to update.
   */
  limit?: number
}

/**
 * PredictionTransaction upsert
 */
export type PredictionTransactionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * The filter to search for the PredictionTransaction to update in case it exists.
   */
  where: Prisma.PredictionTransactionWhereUniqueInput
  /**
   * In case the PredictionTransaction found by the `where` argument doesn't exist, create a new PredictionTransaction with this data.
   */
  create: Prisma.XOR<Prisma.PredictionTransactionCreateInput, Prisma.PredictionTransactionUncheckedCreateInput>
  /**
   * In case the PredictionTransaction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PredictionTransactionUpdateInput, Prisma.PredictionTransactionUncheckedUpdateInput>
}

/**
 * PredictionTransaction delete
 */
export type PredictionTransactionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
  /**
   * Filter which PredictionTransaction to delete.
   */
  where: Prisma.PredictionTransactionWhereUniqueInput
}

/**
 * PredictionTransaction deleteMany
 */
export type PredictionTransactionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PredictionTransactions to delete
   */
  where?: Prisma.PredictionTransactionWhereInput
  /**
   * Limit how many PredictionTransactions to delete.
   */
  limit?: number
}

/**
 * PredictionTransaction without action
 */
export type PredictionTransactionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PredictionTransaction
   */
  select?: Prisma.PredictionTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PredictionTransaction
   */
  omit?: Prisma.PredictionTransactionOmit<ExtArgs> | null
}
