
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserStatus = {
  active: 'active',
  suspend: 'suspend',
  deleted: 'deleted'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const UserRoles = {
  user: 'user',
  admin: 'admin'
} as const

export type UserRoles = (typeof UserRoles)[keyof typeof UserRoles]


export const WalletStatus = {
  active: 'active',
  suspended: 'suspended'
} as const

export type WalletStatus = (typeof WalletStatus)[keyof typeof WalletStatus]


export const Currency = {
  USD: 'USD',
  EUR: 'EUR',
  JPY: 'JPY'
} as const

export type Currency = (typeof Currency)[keyof typeof Currency]


export const WalletTransactionType = {
  deposit: 'deposit',
  withdraw: 'withdraw',
  bet: 'bet',
  payout: 'payout',
  refund: 'refund',
  cancel: 'cancel'
} as const

export type WalletTransactionType = (typeof WalletTransactionType)[keyof typeof WalletTransactionType]


export const MarketStatus = {
  upcoming: 'upcoming',
  opened: 'opened',
  closed: 'closed',
  resolved: 'resolved',
  payout: 'payout',
  cancelled: 'cancelled'
} as const

export type MarketStatus = (typeof MarketStatus)[keyof typeof MarketStatus]


export const PredictionStatus = {
  upcoming: 'upcoming',
  open: 'open',
  resolved: 'resolved',
  won: 'won',
  lost: 'lost',
  cancelled: 'cancelled'
} as const

export type PredictionStatus = (typeof PredictionStatus)[keyof typeof PredictionStatus]


export const PredictionTransactionType = {
  bet: 'bet',
  refund: 'refund',
  cancel: 'cancel'
} as const

export type PredictionTransactionType = (typeof PredictionTransactionType)[keyof typeof PredictionTransactionType]


export const BetStatus = {
  pending: 'pending',
  locked: 'locked',
  won: 'won',
  lost: 'lost',
  payout: 'payout',
  cancelled: 'cancelled'
} as const

export type BetStatus = (typeof BetStatus)[keyof typeof BetStatus]
