
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.js'
export type * from './models/Wallet.js'
export type * from './models/WalletTransaction.js'
export type * from './models/Market.js'
export type * from './models/Prediction.js'
export type * from './models/PredictionTransaction.js'
export type * from './models/Bet.js'
export type * from './commonInputTypes.js'